### ISSUE TITLE
Enable step labels and messages in build config

### ISSUE THREAD

**Issue by briandominick** [DocOps/liquidoc-gem#14]
It would be nice if the build logs could address what steps are being performed using optional labels and descriptions. Let's add a couple of top-level settings to each step in the build.

```yaml
- action: parse
  label: parse-some-stuff
  message: Parsing the stuff we wanted parsed.
  data: data/data.json
  builds:
    - template: templates/stuff_plate.html
       output: out/ourfile.html
```

So logs will reflect the message, and errors will indicate which step was being performed, by step label when one was given.
