### ISSUE TITLE
Enable admission of additional variables to parsing actions as arguments

### ISSUE THREAD

**Issue by briandominick** [DocOps/liquidoc-gem#37]
In addition to small data from fixed files, parse operations should be able to accept additional variables. We want to be able to pass them in through the config file, at the very least, and probably the command line as well. They should be accessible inside templates under the `args.` scope.

```yaml
action: parse
  data: mystuff.yml
  builds:
    properties:
      arguments:
        myvar: someval
        anothervar: another value
    attributes:
      myvar: someval
      another_var: another value
```

This listing illustrates the options I am considering for using an existing build-step setting to pass variables. This format comports to the way `arguments:` are handled in render operations (under `properties:`). But _properties_ in render operations really are about configuring tool settings, not passing content-oriented variables. (That's for _attributes_, an AsciiDoc concept.) Yet since it would be confusing to add another `arguments:` block as an immediate child to `builds:`, I think I'm leaning toward using the `attributes:` block. I need to make sure this is not confusing, because Liquid does not refer to variables as attributes, and AsciiDoc very much does. The really confusing part is that they'll be getting used to generate AsciiDoc files in many cases, yet they will never be used to populate AsciiDoc attribute placeholders, since those are only relevant during AsciiDoc processing.

The command-line option could then use the `-a` option made available for render operations, pretty much the same way its used for attributes (`-a myvar=someval -a another_var='another value'`). I must admit I dig that.

These variables could be accessed like so (example in Liquid):
```liquid
Take {{ args.myvar }} and use it to build {{ args.another_var }}.
```
