### ISSUE TITLE
Enable mutli-file data ingest for parse actions

### ISSUE THREAD

**Issue by briandominick** [DocOps/liquidoc-gem#40]
Why restrict data ingest sources to just one file? Why not:
```yaml
- action: parse
  data:
    - mydata.yml
    - otherdata.json
  build:
    - template: mystuff.liquid
      output: mystuff.html
```
In `mystuff.liquid`, we can access the data in scopes like `mydata.` and `otherdata.`. May need to address namespace collisions; perhaps we default to appending `_<ext>` so for `mystuff.yml` and `mystuff.json`, express as `{{ mystuff_yml.contents }}` and `{{ mystuff_json.morestuff }}`.
