### ISSUE TITLE
Add Tilt integration

### ISSUE THREAD

**Issue by briandominick** [DocOps/liquidoc-gem#41]
I don't know why we're limited to using Liquid templates in parse actions, since the committers at [Tilt](https://github.com/rtomayko/tilt) have done the work of making a universal translator for templating engines, including Liquid, Haml, Handlebars, Slim, and ERB. Let's let user's declare a templating engine, pass the work on to Tilt, and call it a day.

```yaml
- action: parse
  data: mydata.json
  builds:
    - template: _templates/haml/left-nav.html
       engine: haml
       output: _build/left-nav.html
    - template: _template/slim/top-nav.html
       engine: slim
       output: _build/top-nav.html
```
