### ISSUE TITLE
Enable Asciidoctor extensions in config

### ISSUE THREAD

**Issue by briandominick** [DocOps/liquidoc-gem#59]
Render stages should accept a list of required extensions.

```yaml
  builds:
    - output: _build/user-guide.pdf
      doctype: book
      attributes:
        sample_attr: test value
      extensions:
        - git-metadata-preprocessor
        - shell-session-treeprocessor
```
