### ISSUE TITLE
Data object collisions are possible; fix with renaming and catch errors

### ISSUE THREAD

**Issue by briandominick** [DocOps/liquidoc-gem#84]
Now that #40 is implemented, object collisions are possible. I won't go into why I thought this would not be a problem, but it definitely is. One issue is multiple files of the same name being ingested from different paths, such as `platform1/data/product.yml` and `platform2/daata/product.yml.

```yaml
- action: parse
  data:
    - file: platform/data/product.yml
      token: platform
    - file: client/data/product.yml
      token: client
  builds: ...
```
This really means adding the `token:` property to DataSource and making sure that class always processes data file ingest entries. (Not using `object:` as the property name because that namespace may be better used for _ingesting_ data objects in this action, as in #83, in which case you might want to ingest an `object:` by name and rename it with `token:`.

This fix should also incorporate error handling for configured collisions.
